<?php
// $Id: feeds_xpathparser.module,v 1.1.2.3 2010/09/21 09:00:09 twistor Exp $

/**
 * Implementation of hook_feeds_plugins().
 */
function feeds_xpathparser_feeds_plugins() {
  $path = drupal_get_path('module', 'feeds_xpathparser');
  $info = array();

  $info['FeedsXPathParserBase'] = array(
    'hidden'  => TRUE,
    'handler' => array(
      'parent' => 'FeedsParser', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class'  => 'FeedsXPathParserBase',
      'file'   => 'FeedsXPathParser.inc',
      'path'   => $path,
    ),
  );

  $info['FeedsXPathParserHTML'] = array(
    'name'        => t('XPath HTML parser'),
    'description' => t('Parse HTML using XPath.'),
    'handler'     => array(
      'parent' => 'FeedsXPathParserBase', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class'  => 'FeedsXPathParserHTML',
      'file'   => 'FeedsXPathParser.inc',
      'path'   => $path,
    ),
  );

   $info['FeedsXPathParserXML'] = array(
    'name'        => t('XPath XML parser'),
    'description' => t('Parse XML using XPath.'),
    'handler'     => array(
      'parent' => 'FeedsXPathParserBase', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class'  => 'FeedsXPathParserXML',
      'file'   => 'FeedsXPathParser.inc',
      'path'   => $path,
    ),
  );

  return $info;
}

/**
 * Implementation of hook_enable().
 *
 * Clear Feed's plugin cache so that this plugin shows up.
 */
function feeds_xpathparser_enable() {
  cache_clear_all('plugins:feeds:plugins', 'cache');
}
